### ISSUE TITLE
Polymer "inheritance" proposal - expose more mixins!!

### ISSUE THREAD

**Issue by kristianmandrup** [PolymerLabs/polymer-patterns#46]
I fully understand why you wen't away from full components inheritance. A crude weapon indeed.
However it would be VERY convenient if all elements exposed their style, properties and behaviour as mixins for other elements to build on. 

This IS currently possible, so it is only a matter of enhancing existing elements to follow this pattern to allow for better composition. 

This would also help to solve the "problem" with the content selector limitation: https://github.com/Polymer/core-selector/issues/39

Example `paper-scroll-header-panel`

``` js
var mixinElement = Polymer.registry('paper-scroll-header-panel')

Polymer.extend({
  properties: [
    mixinElement.properties, 
    AnotherSetOfproperties, 
  ],
  behaviors: [
    myOtherMixinElement.behaviors,
    someNiceBehavior,
    mixinElement.behaviors
  ]
}, {
  // my specific element overrides and customizations
});
```

You could of course see a behavior as a full set of properties and methods which form a logical unit. Then expose methods and properties as separate mixin units as well. Then allow full inheritance as a convenience, which simply inherits all behaviors and the shared styles exposed by the elements as well.
Provide full flexibility and granular control.

Cheers!

**Comment by kristianmandrup** [comment]
After some research into `polymer` core I see the following methods are already available, however not really documented very well. I guess they could be used as a starting point?

``` js
Polymer.Base

     * @method extend
     * @param {Object} prototype Target object to copy properties to.
     * @param {Object} api Source object to copy properties from.
     * @return {Object} prototype object that was passed as first argument.
     */
    extend: function(prototype, api) {

    /**
     * Copies props from a source object to a target object.
     *
     * Note, this method uses a simple `for...in` strategy for enumerating
     * properties.  To ensure only `ownProperties` are copied from source
     * to target and that accessor implementations are copied, use `extend`.
     *
     * @method mixin
     * @param {Object} target Target object to copy properties to.
     * @param {Object} source Source object to copy properties from.
     * @return {Object} Target object that was passed as first argument.
     */
    mixin: function(target, source) {
      for (var i in source) {
        target[i] = source[i];
      }
      return target;
    },

    copyOwnProperty: function(name, source, target) {

  Polymer.Base.chainObject = function(object, inherited) {
```

**Comment by ebidel** [comment]
This issue was moved to Polymer/polymer#2510
